export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENT_ERROR';
export const SET_INGREDIENT = 'SET_INGREDIENT';

export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const INCREASE_PRICE = 'INCREASE_PRICE';
export const DECREASE_PRICE = 'DECREASE_PRICE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';

export const FETCH_SINGLE_ORDER_START = 'FETCH_SINGLE_ORDER_START';
export const FETCH_SINGLE_ORDER_SUCCESS = 'FETCH_SINGLE_ORDER_SUCCESS';
export const FETCH_SINGLE_ORDER_FAIL = 'FETCH_SINGLE_ORDER_FAIL';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT = 'LOGOUT';