export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENT_ERROR';
export const SET_INGREDIENT = 'SET_INGREDIENT';

export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const INCREASE_PRICE = 'INCREASE_PRICE';
export const DECREASE_PRICE = 'DECREASE_PRICE';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';